# From Thinking in Patterns (with Java) by Bruce Eckel
# At http://www.BruceEckel.com
# (c)2003 Bruce Eckel 
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\com\bruceeckel\util
# using the JDK 1.4 compiler
# Invoke with: make

HOME := ../../../

ifndef MAKECMDGOALS
MAKECMDGOALS := javac
endif

# Command.com is too weak to build this under Windows NT/2000:
ifeq ($(OS),Windows_NT)
COMSPEC=$(SYSTEMROOT)\system32\cmd.exe
endif

ifneq ($(MAKECMDGOALS),clean)
include $(HOME)/$(MAKECMDGOALS).mac
endif

.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

javac: \
	TypedIterator.class \
	StringList.class \
	Generator.class \
	BooleanGenerator.class \
	ByteGenerator.class \
	CharGenerator.class \
	ShortGenerator.class \
	IntGenerator.class \
	LongGenerator.class \
	FloatGenerator.class \
	DoubleGenerator.class \
	Arrays2.class

jikes: \
	TypedIterator.class \
	StringList.class \
	Generator.class \
	BooleanGenerator.class \
	ByteGenerator.class \
	CharGenerator.class \
	ShortGenerator.class \
	IntGenerator.class \
	LongGenerator.class \
	FloatGenerator.class \
	DoubleGenerator.class \
	Arrays2.class

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.class
else
	rm -f *.class
endif


TypedIterator.class: TypedIterator.java 

StringList.class: StringList.java 

Generator.class: Generator.java 

BooleanGenerator.class: BooleanGenerator.java 

ByteGenerator.class: ByteGenerator.java 

CharGenerator.class: CharGenerator.java 

ShortGenerator.class: ShortGenerator.java 

IntGenerator.class: IntGenerator.java 

LongGenerator.class: LongGenerator.java 

FloatGenerator.class: FloatGenerator.java 

DoubleGenerator.class: DoubleGenerator.java 

Arrays2.class: Arrays2.java 

